
#
# This is a list of URLs that Neuberger Berman wants to prevent SOC analysts from blocking
# either by accident or deliberately.
#
# NOTE: As you add to this list, make sure to lower case since ever domain is casted to lower case
#       before being ran against this list.
#

UNBLOCKABLE_URLS = ['360.cn',
                    'amazon.com',
                    'amazonaws.com',
                    'apple.com',
                    'baidu.com',
                    'bankofamerica.com',
                    'bing.com',
                    'blogspot.com',
                    'chase.com',
                    'cnn.com',
                    'craigslist.org',
                    'dropbox.com',
                    'ebay.com',
                    'espn.com',
                    'force.com',
                    'github.com',
                    'google.com',
                    'imdb.com',
                    'instagram.com',
                    'instructure.com',
                    'intuit.com',
                    'linkedin.com',
                    'live.com',
                    'microsoft.com',
                    'microsoftonline.com',
                    'ytimes.com',
                    'office.com',
                    'paypal.com',
                    'qq.com',
                    'reddit.com',
                    'salesforce.com',
                    'servicenow.com',
                    'stackoverflow.com',
                    'statestreet.com',
                    'walmart.com',
                    'weather.com',
                    'weibo.com',
                    'wellsfargo.com',
                    'wikipedia.org',
                    'workday.com',
                    'wsj.com',
                    'yahoo.co.jp',
                    'yahoo.com',
                    'yandex.ru',
                    'yelp.com',
                    'youtube.com',
                    'zillow.com',
                    'adp.com',
                    'bloomberg.com',
                    'reuters.com']
